### ISSUE TITLE
secrets.toml file is missing and throws error

### ISSUE THREAD

**Issue by kkacstudent** [neo4j-examples/rag-demo#25]
poetry update does not work

Unable to read the lock file (Invalid statement (at line 1445, column 1)).

====

pipenv run throws below error

2024-03-08 07:34:34.806 Uncaught app exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/rag-demo-4DIJ41Uf/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/ubuntu/rag-demo/rag_demo/main.py", line 1, in <module>
    from analytics import track
  File "/home/ubuntu/rag-demo/rag_demo/analytics.py", line 8, in <module>
    analytics.write_key = st.secrets["SEGMENT_WRITE_KEY"]
                          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/rag-demo-4DIJ41Uf/lib/python3.11/site-packages/streamlit/runtime/secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
            ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/virtualenvs/rag-demo-4DIJ41Uf/lib/python3.11/site-packages/streamlit/runtime/secrets.py", line 214, in _parse
    raise FileNotFoundError(err_msg)
FileNotFoundError: No secrets files found. Valid paths for a secrets.toml file are: /home/ubuntu/.streamlit/secrets.toml, /home/ubuntu/rag-demo/.streamlit/secrets.toml

**Comment by jalakoo** [comment]
Thanks for raising @kkacstudent.

 Fixes added to the [update_dependencies](https://github.com/neo4j-examples/rag-demo/tree/update_dependencies) branch:
 - pipenv dependencies updated
 - analytics now optional
 - secrets.toml.example key for the SEGMENT_WRITE_KEY corrected
 - Instructions added in README.md regarding needing to copy the secrets.toml.example as secrets.toml for Streamlit to run
 
 This branch will be merged with main after we've finished review and testing.

**Comment by kkacstudent** [comment]
Not able to find the branch update_dependencies shared above. Also related to the README could not find the file secrets.toml.example. Sorry if I missed anything.
